# Cleaning Data

In [60]:
import pandas as pd 
import numpy as np

In [61]:
# load data
df = pd.read_csv("../data/raw/cars_from_japan_1_521.csv")
df.head()

,name,registration_year,mileage,model_code,engine,grade,transmission,price
0,2021 DAIHATSU HIJET TRUCK 3BD-S510P,2021 / Jul,"56,000km",3BD-S510P,660cc,-,Automatic,"US$ 7,929"
1,2021 MERCEDES-BENZ AMG 3BA-463276 4WD,2021 / May,"10,000km",3BA-463276,"4,000cc",4.5,Automatic,"US$ 126,540"
2,2019 TOYOTA RAV4 6AA-AXAH54 4WD,2019 / Dec,"37,300km",6AA-AXAH54,"2,500cc",-,Automatic,"US$ 19,142"
3,2019 TOYOTA RAV4 MXAA52,2019 / Nov,"14,700km",MXAA52,"2,000cc",-,Automatic,"US$ 20,910"
4,2019 TOYOTA RAV4 6BA-MXAA54 4WD,2019 / Nov,"21,900km",6BA-MXAA54,"2,000cc",-,Automatic,"US$ 16,940"

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 13000 entries, 0 to 12999
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   name               13000 non-null  str
 1   registration_year  13000 non-null  str
 2   mileage            13000 non-null  str
 3   model_code         13000 non-null  str
 4   engine             13000 non-null  str
 5   grade              13000 non-null  str
 6   transmission       13000 non-null  str
 7   price              12849 non-null  str
dtypes: str(8)
memory usage: 812.6 KB

### Clean name column

In [62]:
parts = df["name"].str.split(" ", n=2, expand=True)

df['make'] = parts[1]
df['model'] = parts[2]

KNOWN_MAKES = [
    "MERCEDES-BENZ",
    "LAND ROVER",
    "ALFA ROMEO",
    "ASTON MARTIN",
    "ROLLS-ROYCE",
    "VOLKSWAGEN",
    "MITSUBISHI",
    "CHEVROLET",
    "LAMBORGHINI",
    "MASERATI",
    "DAIHATSU",
    "TOYOTA",
    "SUBARU",
    "SUZUKI",
    "NISSAN",
    "PORSCHE",
    "PEUGEOT",
    "RENAULT",
    "TESLA",
    "LEXUS",
    "HONDA",
    "VOLVO",
    "MAZDA",
    "JEEP",
    "BMW",
    "AUDI",
    "MINI",
    "FIAT",
]

In [64]:
def extract_make(name):
    name = name.upper()

    for make in KNOWN_MAKES:
        if make in name:
            return make

    return "OTHER"

df["make"] = df["name"].apply(extract_make)

In [65]:
df[['make','model']]

                make                        model
0           DAIHATSU        HIJET TRUCK 3BD-S510P
1      MERCEDES-BENZ           AMG 3BA-463276 4WD
2             TOYOTA          RAV4 6AA-AXAH54 4WD
3             TOYOTA                  RAV4 MXAA52
4             TOYOTA          RAV4 6BA-MXAA54 4WD
...              ...                          ...
12995         TOYOTA  HIACE VAN QDF-GDH206Kカイ 4WD
12996            BMW       2 SERIES 3BA-6V15W 2WD
12997         SUBARU         FORESTER 4BA-SK5 4WD
12998         TOYOTA       HARRIER 6AA-AXUH85 4WD
12999         TOYOTA              RAV4 MXAA54 4WD

[13000 rows x 2 columns]

In [67]:
df['make'].unique()

<StringArray>
[     'DAIHATSU', 'MERCEDES-BENZ',        'TOYOTA',        'SUBARU',
           'BMW',        'NISSAN',        'SUZUKI',         'MAZDA',
         'VOLVO',    'VOLKSWAGEN',         'HONDA',    'LAND ROVER',
    'MITSUBISHI',          'MINI',         'OTHER',         'LEXUS',
       'PORSCHE',          'AUDI',          'JEEP',          'FIAT',
      'MASERATI',   'LAMBORGHINI',    'ALFA ROMEO',         'TESLA',
       'PEUGEOT',     'CHEVROLET',       'RENAULT',  'ASTON MARTIN']
Length: 28, dtype: str

### Clean mileage column

In [68]:
df["mileage"]

0        56,000km
1        10,000km
2        37,300km
3        14,700km
4        21,900km
           ...
12995    28,000km
12996    13,000km
12997    31,700km
12998    22,000km
12999    12,400km
Name: mileage, Length: 13000, dtype: str

In [69]:
df["mileage_km"] = df["mileage"].str.replace(",", "", regex=False).str.replace("km", "", regex=False)

In [70]:
df["mileage_km"] = pd.to_numeric(df["mileage_km"], errors="coerce")

In [71]:
df["mileage_km"]

0        56000.0
1        10000.0
2        37300.0
3        14700.0
4        21900.0
          ...
12995    28000.0
12996    13000.0
12997    31700.0
12998    22000.0
12999    12400.0
Name: mileage_km, Length: 13000, dtype: float64

### Clean engine_cc columns

In [72]:
df['engine']

0          660cc
1        4,000cc
2        2,500cc
3        2,000cc
4        2,000cc
          ...
12995    2,800cc
12996    1,500cc
12997    1,800cc
12998    2,500cc
12999    2,000cc
Name: engine, Length: 13000, dtype: str

In [73]:
df["engine_cc"] = (
    df["engine"]\
    .str.replace(",", "", regex=False)\
    .str.replace("cc", "", regex=False)
)

In [74]:
df["engine_cc"] = pd.to_numeric(df["engine_cc"], errors="coerce")

In [75]:
df['engine_cc']

0         660
1        4000
2        2500
3        2000
4        2000
         ...
12995    2800
12996    1500
12997    1800
12998    2500
12999    2000
Name: engine_cc, Length: 13000, dtype: int64

### Clean registration_year column

In [76]:
df['registration_year']

0        2021 / Jul
1        2021 / May
2        2019 / Dec
3        2019 / Nov
4        2019 / Nov
            ...
12995    2019 / Sep
12996    2022 / Feb
12997    2021 / Mar
12998    2020 / Jun
12999    2019 / Oct
Name: registration_year, Length: 13000, dtype: str

In [77]:
df["year"] = df["registration_year"].str.extract(r"(\d{4})").astype(int)
df["year"]

0        2021
1        2021
2        2019
3        2019
4        2019
         ...
12995    2019
12996    2022
12997    2021
12998    2020
12999    2019
Name: year, Length: 13000, dtype: int64

### Clean grade columns

In [78]:
df['grade']

0          -
1        4.5
2          -
3          -
4          -
        ...
12995      4
12996      -
12997      -
12998      4
12999      -
Name: grade, Length: 13000, dtype: str

In [79]:
# convert `-` to NaN, then numeric
df["grade"] = df["grade"].replace("-", np.nan)

df["grade"] = pd.to_numeric(df["grade"], errors="coerce")

In [80]:
df['grade']

0        NaN
1        4.5
2        NaN
3        NaN
4        NaN
        ...
12995    4.0
12996    NaN
12997    NaN
12998    4.0
12999    NaN
Name: grade, Length: 13000, dtype: float64

### Clean price columns

In [81]:
df['price']

0          US$ 7,929
1        US$ 126,540
2         US$ 19,142
3         US$ 20,910
4         US$ 16,940
            ...
12995     US$ 37,150
12996     US$ 25,207
12997     US$ 18,300
12998     US$ 23,965
12999     US$ 20,321
Name: price, Length: 13000, dtype: str

In [82]:
df["price_usd"] = (
    df["price"]
    .str.replace("US$", "", regex=False)
    .str.replace(",", "", regex=False)
)
df["price_usd"] = pd.to_numeric(df["price_usd"], errors="coerce")

In [83]:
df['price_usd']

0          7929.0
1        126540.0
2         19142.0
3         20910.0
4         16940.0
           ...
12995     37150.0
12996     25207.0
12997     18300.0
12998     23965.0
12999     20321.0
Name: price_usd, Length: 13000, dtype: float64

## Final Clean dataset

In [84]:
clean_df = df[[
    "year",
    "make",
    "model_code",
    "mileage_km",
    "engine_cc",
    "transmission",
    "grade",
    "price_usd"
]]

In [85]:
clean_df

,year,make,model_code,mileage_km,engine_cc,transmission,grade,price_usd
0,2021,DAIHATSU,3BD-S510P,56000.0,660,Automatic,NaN,7929.0
1,2021,MERCEDES-BENZ,3BA-463276,10000.0,4000,Automatic,4.5,126540.0
2,2019,TOYOTA,6AA-AXAH54,37300.0,2500,Automatic,NaN,19142.0
3,2019,TOYOTA,MXAA52,14700.0,2000,Automatic,NaN,20910.0
4,2019,TOYOTA,6BA-MXAA54,21900.0,2000,Automatic,NaN,16940.0
...,...,...,...,...,...,...,...,...
12995,2019,TOYOTA,QDF-GDH206Kカイ,28000.0,2800,Automatic,4.0,37150.0
12996,2022,BMW,3BA-6V15W,13000.0,1500,Automatic,NaN,25207.0
12997,2021,SUBARU,4BA-SK5,31700.0,1800,Automatic,NaN,18300.0
12998,2020,TOYOTA,6AA-AXUH85,22000.0,2500,Automatic,4.0,23965.0
12999,2019,TOYOTA,MXAA54,12400.0,2000,Automatic,NaN,20321.0

In [86]:
clean_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 13000 entries, 0 to 12999
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   year          13000 non-null  int64
 1   make          13000 non-null  str
 2   model_code    13000 non-null  str
 3   mileage_km    12875 non-null  float64
 4   engine_cc     13000 non-null  int64
 5   transmission  13000 non-null  str
 6   grade         5358 non-null   float64
 7   price_usd     12849 non-null  float64
dtypes: float64(3), int64(2), str(3)
memory usage: 812.6 KB

## Save clean dataset

In [87]:
clean_df.to_csv("../data/clean/clean_cars_from_japan.csv", index=False)